(() => {
  const PREFIX="lutron-v28-"; const palette=["#36d6c5","#f6b94a","#4c9cff","#fb7185","#a3e635","#c084fc","#f97316","#14b8a6"];
  const state={peer:null,connection:null,code:"",retry:null,attempt:0,session:0,readings:new Map(),sourceOrder:new Map()};
  const $=id=>document.getElementById(id), form=$("pairForm"), input=$("pairCode"), status=$("pairStatus"), badge=$("connectionBadge"), cards=$("cards"), empty=$("emptyState");
  const setStatus=(text,type="waiting")=>{status.textContent=text;badge.textContent=text;badge.className=`status ${type}`};
  const stop=message=>{state.session++;if(state.retry)clearTimeout(state.retry);state.retry=null;try{state.connection?.close()}catch{}try{state.peer?.destroy()}catch{}state.peer=null;state.connection=null;state.attempt=0;$("stopButton").hidden=true;if(message)setStatus(message,"waiting")};
  const retry=()=>{if(!state.code||state.retry)return;const token=state.session,delay=Math.min(5000,1500+state.attempt++*750);setStatus("遠端連線已中斷，正在重新連線…","retrying");state.retry=setTimeout(()=>{state.retry=null;if(token===state.session)connect(token)},delay)};
  function connect(token=state.session){if(!state.code||token!==state.session)return;try{state.peer?.destroy()}catch{}const peer=state.peer=new Peer();peer.on("open",()=>{if(token!==state.session)return;const c=state.connection=peer.connect(PREFIX+state.code,{reliable:true});c.on("open",()=>{state.attempt=0;setStatus("遠端已連線","connected");$("stopButton").hidden=false});c.on("data",receive);c.on("close",retry);c.on("error",retry)});peer.on("disconnected",retry);peer.on("error",retry)}
  function receive(payload){if(payload?.type!=="readings"||!Array.isArray(payload.readings))return;const source=String(payload.alias||"REMOTE"), sourceColor=payload.color||palette[0], sourceKey=`${source}|${sourceColor}`;if(!state.sourceOrder.has(sourceKey))state.sourceOrder.set(sourceKey,state.sourceOrder.size);payload.readings.forEach((r,i)=>{const channel=String(r.displayCode??r.channelIndex??r.id??i+1), color=r.lineColor||sourceColor, key=`${sourceKey}|${channel}`;state.readings.set(key,{...r,id:channel,source,sourceKey,sourceIndex:state.sourceOrder.get(sourceKey),channel,color})});render()}
  const n=v=>v===undefined||v===null||v===""?"--":String(v); const sorter=new Intl.Collator(undefined,{numeric:true,sensitivity:"base"}); function render(){const data=[...state.readings.values()].sort((a,b)=>a.sourceIndex-b.sourceIndex||sorter.compare(a.channel,b.channel));const sources=[...new Set(data.map(r=>r.source))];empty.hidden=data.length>0;cards.innerHTML="";$("sampleCount").textContent=`${data.length} 個通道`;$("sourceLabel").textContent=sources.length?`來源：${sources.join("、")}`:"等待發射端資料";for(const r of data){const el=document.createElement("article");el.className="measurement";el.style.setProperty("--source",r.color||palette[0]);const name=r.name||r.label||r.displayName||r.displayCode||"Channel";const unit=r.unit||"";const value=n(r.value??r.displayValue);el.innerHTML=`<div class="channel">${escape(`${r.source}-${r.displayCode||r.channel}`)}</div><div class="name">${escape(name)}</div><div class="value">${escape(value)}<span class="unit">${escape(unit)}</span></div><div class="meta">即時資料</div>`;cards.append(el)}}
  const escape=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
  input.addEventListener("input",()=>input.value=input.value.replace(/\D/g,"").slice(0,6));form.addEventListener("submit",e=>{e.preventDefault();const code=input.value;if(code.length!==6){setStatus("請輸入正確的 6 位配對碼","failed");return}stop();state.code=code;state.session++;setStatus("正在加入遠端監看…","waiting");connect(state.session)});$("stopButton").addEventListener("click",()=>{stop("遠端連線已停止");state.code=""});
})();


