(() => {
const PREFIX="lutron-v28-",palette=["#36d6c5","#f6b94a","#4c9cff","#fb7185","#a3e635","#c084fc","#f97316","#14b8a6"],sorter=new Intl.Collator(undefined,{numeric:true,sensitivity:"base"}),OPTION_KEY="lutron-remote-channel-options-v1";
const state={peer:null,connection:null,code:"",retry:null,attempt:0,session:0,readings:new Map(),sourceOrder:new Map(),stats:new Map(),alarms:new Map(),options:new Map(),logs:[],logger:null,editing:null,audio:null,lastBeep:0};
const $=id=>document.getElementById(id),form=$("pairForm"),input=$("pairCode"),status=$("pairStatus"),badge=$("connectionBadge"),cards=$("cards"),empty=$("emptyState"),optionsPanel=$("channelOptions");
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const setStatus=(t,k="waiting")=>{status.textContent=t;badge.textContent=t;badge.className=`status ${k}`};
let savedOptions={};try{savedOptions=JSON.parse(localStorage.getItem(OPTION_KEY)||"{}")}catch{}
function optionFor(key){if(!state.options.has(key)){const old=savedOptions[key]||{};state.options.set(key,{visible:old.visible!==false,logging:old.logging!==false})}return state.options.get(key)}
function saveOptions(){const out={};for(const [key,value] of state.options)out[key]=value;try{localStorage.setItem(OPTION_KEY,JSON.stringify(out))}catch{}}
function changeOption(key,field,value){optionFor(key)[field]=value;saveOptions();render()}
function stop(message){state.session++;clearTimeout(state.retry);state.retry=null;try{state.connection?.close()}catch{}try{state.peer?.destroy()}catch{}state.peer=null;state.connection=null;state.attempt=0;$("stopButton").hidden=true;if(message)setStatus(message)}
function retry(){if(!state.code||state.retry)return;const token=state.session,delay=Math.min(5000,1500+state.attempt++*750);setStatus("遠端連線已中斷，正在重新連線…","retrying");state.retry=setTimeout(()=>{state.retry=null;if(token===state.session)connect(token)},delay)}
function connect(token=state.session){if(!state.code||token!==state.session)return;try{state.peer?.destroy()}catch{}const peer=state.peer=new Peer();peer.on("open",()=>{if(token!==state.session)return;const c=state.connection=peer.connect(PREFIX+state.code,{reliable:true});c.on("open",()=>{state.attempt=0;setStatus("遠端已連線","connected");$("stopButton").hidden=false});c.on("data",receive);c.on("close",retry);c.on("error",retry)});peer.on("disconnected",retry);peer.on("error",retry)}
function receive(payload){if(payload?.type!=="readings"||!Array.isArray(payload.readings))return;const source=String(payload.alias||"REMOTE"),sourceColor=payload.color||palette[0],sourceKey=`${source}|${sourceColor}`;if(!state.sourceOrder.has(sourceKey))state.sourceOrder.set(sourceKey,state.sourceOrder.size);payload.readings.forEach((r,i)=>{const channel=String(r.displayCode??r.channelIndex??r.id??i+1),color=r.lineColor||sourceColor,key=`${sourceKey}|${channel}`,raw=Number(r.value??r.displayValue);state.readings.set(key,{...r,key,source,sourceColor,channel,color,sourceIndex:state.sourceOrder.get(sourceKey)});optionFor(key);if(Number.isFinite(raw)){const s=state.stats.get(key)||{min:raw,max:raw,sum:0,count:0};s.min=Math.min(s.min,raw);s.max=Math.max(s.max,raw);s.sum+=raw;s.count++;state.stats.set(key,s)}});render()}
function alarming(r){const a=state.alarms.get(r.key),v=Number(r.value??r.displayValue);return !!a&&Number.isFinite(v)&&((Number.isFinite(a.low)&&v<a.low)||(Number.isFinite(a.high)&&v>a.high))}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!state.audio)state.audio=new C();const o=state.audio.createOscillator(),g=state.audio.createGain();o.frequency.value=880;g.gain.setValueAtTime(.08,state.audio.currentTime);o.connect(g).connect(state.audio.destination);o.start();o.stop(state.audio.currentTime+.16)}catch{}}
function allReadings(){return [...state.readings.values()].sort((a,b)=>a.sourceIndex-b.sourceIndex||sorter.compare(a.channel,b.channel))}
function renderOptions(data){if(!data.length){optionsPanel.innerHTML='<p class="settings-empty">等待通道資料。</p>';return}optionsPanel.innerHTML=data.map(r=>{const opt=optionFor(r.key),id=encodeURIComponent(r.key),label=`${r.source}-${r.displayCode||r.channel}｜${r.name||r.label||r.displayName||"Channel"}`;return `<label class="channel-option" style="--source:${esc(r.color)}"><span class="option-name">${esc(label)}</span><span><input type="checkbox" data-key="${id}" data-field="visible" ${opt.visible?"checked":""}> 顯示</span><span><input type="checkbox" data-key="${id}" data-field="logging" ${opt.logging?"checked":""}> 記錄</span></label>`}).join("");optionsPanel.querySelectorAll("input").forEach(box=>box.onchange=()=>changeOption(decodeURIComponent(box.dataset.key),box.dataset.field,box.checked))}
function render(){const data=allReadings(),visible=data.filter(r=>optionFor(r.key).visible),sources=[...new Set(data.map(r=>r.source))];empty.hidden=visible.length>0;empty.textContent=data.length&&!visible.length?"所有通道目前皆為隱藏；可在下方「通道顯示與記錄」勾選顯示。":"完成配對後，量測通道會顯示於此處。";cards.innerHTML="";$("sampleCount").textContent=`${visible.length}/${data.length} 個通道`;$("sourceLabel").textContent=sources.length?`來源：${sources.join("、")}`:"等待發射端資料";let alarm=false;for(const r of visible){const st=state.stats.get(r.key),unit=r.unit||"",value=r.value??r.displayValue??"--",hit=alarming(r);alarm||=hit;const el=document.createElement("article");el.className=`measurement${hit?" alarm":""}`;el.style.setProperty("--source",r.color);el.onclick=()=>openAlarm(r);el.innerHTML=`<div class="channel">${esc(`${r.source}-${r.displayCode||r.channel}`)}</div><div class="name">${esc(r.name||r.label||r.displayName||r.displayCode||"Channel")}</div><div class="value">${esc(value)}<span class="unit">${esc(unit)}</span></div><div class="meta"><span>最高: ${st?st.max.toFixed(2):"--"}</span><span>最低: ${st?st.min.toFixed(2):"--"}</span><span>平均: ${st?(st.sum/st.count).toFixed(2):"--"}</span></div>`;cards.append(el)}renderOptions(data);if(alarm&&Date.now()-state.lastBeep>1000){state.lastBeep=Date.now();beep()}}
function openAlarm(r){state.editing=r;const a=state.alarms.get(r.key)||{};$("alarmTitle").textContent=`${r.source}-${r.displayCode||r.channel} Alarm`;$("alarmUnit").textContent=r.unit?`單位：${r.unit}`:"";$("lowAlarm").value=Number.isFinite(a.low)?a.low:"";$("highAlarm").value=Number.isFinite(a.high)?a.high:"";$("alarmDialog").showModal()}
$("alarmForm").addEventListener("submit",e=>{e.preventDefault();const r=state.editing,lowText=$("lowAlarm").value.trim(),highText=$("highAlarm").value.trim(),low=lowText===""?undefined:Number(lowText),high=highText===""?undefined:Number(highText);if(r){if(Number.isFinite(low)||Number.isFinite(high))state.alarms.set(r.key,{low:Number.isFinite(low)?low:undefined,high:Number.isFinite(high)?high:undefined});else state.alarms.delete(r.key)}$("alarmDialog").close();render()});$("clearAlarm").onclick=()=>{if(state.editing)state.alarms.delete(state.editing.key);$("alarmDialog").close();render()};
function columnName(r){return `${r.source} (${r.sourceColor}) - ${r.displayCode||r.channel}`}
function snapshot(){const row={time:new Date().toLocaleString("sv-SE"),values:{}};for(const r of allReadings())if(optionFor(r.key).logging)row.values[columnName(r)]=r.value??r.displayValue??"";state.logs.push(row);$("loggerInfo").textContent=`已記錄 ${state.logs.length} 筆資料。`;$("exportCsv").disabled=!state.logs.length}
$("loggerToggle").onclick=()=>{if(state.logger){clearInterval(state.logger);state.logger=null;$("loggerToggle").textContent="▶ 開始記錄";$("loggerInfo").textContent=`記錄已停止，共 ${state.logs.length} 筆。`}else{snapshot();state.logger=setInterval(snapshot,Number($("loggerInterval").value));$("loggerToggle").textContent="■ 停止記錄";$("loggerInfo").textContent="記錄中…"}};
$("exportCsv").onclick=()=>{const cols=[...new Set(state.logs.flatMap(x=>Object.keys(x.values)))],csv=[["時間",...cols],...state.logs.map(x=>[x.time,...cols.map(c=>x.values[c]??"")])].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"}));a.download=`Lutron-Remote-${Date.now()}.csv`;a.click();URL.revokeObjectURL(a.href)};
function resetForNewPair(){if(state.logger){clearInterval(state.logger);state.logger=null;$("loggerToggle").textContent="▶ 開始記錄"}state.readings.clear();state.sourceOrder.clear();state.stats.clear();state.logs=[];$("exportCsv").disabled=true;$("loggerInfo").textContent="尚未開始記錄。";render()}
input.oninput=()=>input.value=input.value.replace(/\D/g,"").slice(0,6);form.onsubmit=e=>{e.preventDefault();if(input.value.length!==6){setStatus("請輸入正確的 6 位配對碼","failed");return}stop();resetForNewPair();state.code=input.value;state.session++;setStatus("正在加入遠端監看…");connect(state.session)};$("stopButton").onclick=()=>{stop("遠端連線已停止");state.code=""};
})();
