(() => {
const PREFIX="lutron-v28-",palette=["#36d6c5","#f6b94a","#4c9cff","#fb7185","#a3e635","#c084fc","#f97316","#14b8a6"],sorter=new Intl.Collator(undefined,{numeric:true,sensitivity:"base"}),OPTION_KEY="lutron-remote-channel-options-v1";
const state={peer:null,connection:null,code:"",retry:null,attempt:0,session:0,readings:new Map(),sourceOrder:new Map(),stats:new Map(),alarms:new Map(),options:new Map(),logs:[],logger:null,editing:null,audio:null,lastBeep:0};
const $=id=>document.getElementById(id),form=$("pairForm"),input=$("pairCode"),status=$("pairStatus"),badge=$("connectionBadge"),cards=$("cards"),empty=$("emptyState"),optionsPanel=$("channelOptions"),alarmBanner=$("alarmBanner"),logTableWrap=$("logTableWrap"),logResizeHandle=$("logResizeHandle");
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
const setStatus=(t,k="waiting")=>{status.textContent=t;badge.textContent=t;badge.className=`status ${k}`};
let savedOptions={};try{savedOptions=JSON.parse(localStorage.getItem(OPTION_KEY)||"{}")}catch{}
function optionFor(key){if(!state.options.has(key)){const old=savedOptions[key]||{};state.options.set(key,{visible:old.visible!==false})}return state.options.get(key)}
function saveOptions(){const out={};for(const [key,value] of state.options)out[key]=value;try{localStorage.setItem(OPTION_KEY,JSON.stringify(out))}catch{}}
function changeOption(key,field,value){optionFor(key)[field]=value;saveOptions();render()}
function numberOf(reading){for(const raw of [reading?.value,reading?.displayValue,reading?.canonicalValue,reading?.numericValue,reading?.reading]){if(typeof raw==="number"&&Number.isFinite(raw))return raw;if(typeof raw==="string"){const cleaned=raw.replace(/,/g,"").trim(),number=Number(cleaned);if(Number.isFinite(number))return number;const matched=cleaned.match(/[-+]?\d*\.?\d+(?:e[-+]?\d+)?/i);if(matched){const parsed=Number(matched[0]);if(Number.isFinite(parsed))return parsed}}}return NaN}
function stop(message){state.session++;clearTimeout(state.retry);state.retry=null;try{state.connection?.close()}catch{}try{state.peer?.destroy()}catch{}state.peer=null;state.connection=null;state.attempt=0;$("stopButton").hidden=true;if(message)setStatus(message)}
function retry(){if(!state.code||state.retry)return;const token=state.session,delay=Math.min(5000,1500+state.attempt++*750);setStatus("遠端連線已中斷，正在重新連線…","retrying");state.retry=setTimeout(()=>{state.retry=null;if(token===state.session)connect(token)},delay)}
function connect(token=state.session){if(!state.code||token!==state.session)return;try{state.peer?.destroy()}catch{}const peer=state.peer=new Peer();peer.on("open",()=>{if(token!==state.session)return;const c=state.connection=peer.connect(PREFIX+state.code,{reliable:true});c.on("open",()=>{state.attempt=0;setStatus("遠端已連線","connected");$("stopButton").hidden=false});c.on("data",receive);c.on("close",retry);c.on("error",retry)});peer.on("disconnected",retry);peer.on("error",retry)}
function receive(payload){if(payload?.type!=="readings"||!Array.isArray(payload.readings))return;const source=String(payload.alias||"REMOTE"),sourceColor=payload.color||palette[0],sourceKey=`${source}|${sourceColor}`;if(!state.sourceOrder.has(sourceKey))state.sourceOrder.set(sourceKey,state.sourceOrder.size);payload.readings.forEach((r,i)=>{const channel=String(r.displayCode??r.channelIndex??r.id??i+1),color=r.lineColor||sourceColor,key=`${sourceKey}|${channel}`,raw=numberOf(r);state.readings.set(key,{...r,key,source,sourceColor,channel,color,sourceIndex:state.sourceOrder.get(sourceKey)});optionFor(key);if(Number.isFinite(raw)){const s=state.stats.get(key)||{min:raw,max:raw,sum:0,count:0};s.min=Math.min(s.min,raw);s.max=Math.max(s.max,raw);s.sum+=raw;s.count++;state.stats.set(key,s)}});render()}
function alarming(r){const a=state.alarms.get(r.key);if(!a)return false;const shown=r.value??r.displayValue??r.canonicalValue??r.numericValue??r.reading,v=numberOf({displayValue:shown}),low=Number(a.low),high=Number(a.high),hasLow=a.low!==undefined&&a.low!==""&&Number.isFinite(low),hasHigh=a.high!==undefined&&a.high!==""&&Number.isFinite(high);return Number.isFinite(v)&&((hasLow&&v<low)||(hasHigh&&v>high))}
function prepareAudio(){try{const C=window.AudioContext||window.webkitAudioContext;if(!state.audio)state.audio=new C();state.audio.resume?.()}catch{}}
function beep(){try{prepareAudio();const o=state.audio.createOscillator(),g=state.audio.createGain();o.frequency.value=880;g.gain.setValueAtTime(.09,state.audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,state.audio.currentTime+.28);o.connect(g).connect(state.audio.destination);o.start();o.stop(state.audio.currentTime+.3)}catch{}}
function allReadings(){return [...state.readings.values()].sort((a,b)=>a.sourceIndex-b.sourceIndex||sorter.compare(a.channel,b.channel))}
function displayId(r){return `${r.source} - ${r.displayCode||r.channel}`}
function renderOptions(data){if(!data.length){optionsPanel.innerHTML='<p class="settings-empty">等待通道資料。</p>';return}optionsPanel.innerHTML=data.map((r,index)=>{const opt=optionFor(r.key),id=encodeURIComponent(r.key),label=r.name||r.label||r.displayName||`Channel ${r.displayCode||r.channel}`;return `<label class="channel-option" style="--source:${esc(r.color)}"><input type="checkbox" data-key="${id}" data-field="visible" ${opt.visible?"checked":""}><span class="option-index">${index+1}</span><span class="option-name">${esc(label)}</span></label>`}).join("");optionsPanel.querySelectorAll("input").forEach(box=>box.onchange=()=>changeOption(decodeURIComponent(box.dataset.key),box.dataset.field,box.checked))}
function renderLogs(){const rows=[...state.logs].reverse(),cols=[...new Set(state.logs.flatMap(x=>Object.keys(x.values)))],resizable=state.logs.length>=10;$("logCount").textContent=`${state.logs.length} 筆`;logTableWrap.classList.toggle("is-resizable",resizable);logResizeHandle.hidden=!resizable;if(!rows.length){logTableWrap.innerHTML='<p class="settings-empty">開始記錄後，資料會顯示於此處。</p>';return}logTableWrap.innerHTML=`<table class="log-table"><thead><tr><th>時間</th>${cols.map(c=>`<th>${esc(c)}</th>`).join("")}</tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row.time)}</td>${cols.map(c=>`<td>${esc(row.values[c]??"")}</td>`).join("")}</tr>`).join("")}</tbody></table>`}
function render(){const data=allReadings(),visible=data.filter(r=>optionFor(r.key).visible),sources=[...new Set(data.map(r=>r.source))],hits=data.filter(alarming);empty.hidden=visible.length>0;empty.textContent=data.length&&!visible.length?"所有通道目前皆未勾選；可在下方「讀取通道」勾選要顯示與記錄的 CH。":"完成配對後，量測通道會顯示於此處。";cards.innerHTML="";$("sampleCount").textContent=`${visible.length}/${data.length} 個通道`;$("sourceLabel").textContent=sources.length?`來源：${sources.join("、")}`:"等待發射端資料";alarmBanner.hidden=!hits.length;alarmBanner.textContent=hits.length?`⚠ ALARM：${hits.map(displayId).join("、")} 超出設定範圍` : "";for(const r of visible){const st=state.stats.get(r.key),unit=r.unit||"",value=r.value??r.displayValue??"--",hit=alarming(r),a=state.alarms.get(r.key);const el=document.createElement("article");el.className=`measurement${hit?" alarm":""}`;el.style.setProperty("--source",r.color);el.onclick=()=>openAlarm(r);el.innerHTML=`<div class="channel">${esc(displayId(r))}</div><div class="name">${esc(r.name||r.label||r.displayName||r.displayCode||"Channel")}</div><div class="value">${esc(value)}<span class="unit">${esc(unit)}</span></div><div class="meta"><span>最高: ${st?st.max.toFixed(2):"--"}</span><span>最低: ${st?st.min.toFixed(2):"--"}</span><span>平均: ${st?(st.sum/st.count).toFixed(2):"--"}</span></div>${a?`<div class="alarm-limits">Alarm：${Number.isFinite(a.low)?`低 ${a.low}`:""}${Number.isFinite(a.low)&&Number.isFinite(a.high)?"　":""}${Number.isFinite(a.high)?`高 ${a.high}`:""}</div>`:""}`;cards.append(el)}renderOptions(data);renderLogs();if(hits.length&&Date.now()-state.lastBeep>1000){state.lastBeep=Date.now();beep()}}
function openAlarm(r){state.editing=r;const a=state.alarms.get(r.key)||{};$("alarmTitle").textContent=`${displayId(r)} Alarm`;$("alarmUnit").textContent=r.unit?`單位：${r.unit}`:"";$("lowAlarm").value=Number.isFinite(a.low)?a.low:"";$("highAlarm").value=Number.isFinite(a.high)?a.high:"";$("alarmDialog").showModal()}
$("alarmForm").addEventListener("submit",e=>{e.preventDefault();prepareAudio();const r=state.editing,lowText=$("lowAlarm").value.trim(),highText=$("highAlarm").value.trim(),low=lowText===""?undefined:Number(lowText),high=highText===""?undefined:Number(highText);if(r){if(Number.isFinite(low)||Number.isFinite(high))state.alarms.set(r.key,{low:Number.isFinite(low)?low:undefined,high:Number.isFinite(high)?high:undefined});else state.alarms.delete(r.key)}$("alarmDialog").close();render()});$("clearAlarm").onclick=()=>{if(state.editing)state.alarms.delete(state.editing.key);$("alarmDialog").close();render()};
function snapshot(){const row={time:new Date().toLocaleString("sv-SE"),values:{},units:{}};for(const r of allReadings())if(optionFor(r.key).visible){let column=displayId(r);if(Object.hasOwn(row.values,column))column=`${column}（來源 ${r.sourceIndex+1}）`;row.values[column]=r.value??r.displayValue??"";row.units[column]=r.unit||""}state.logs.push(row);$("loggerInfo").textContent=`已記錄 ${state.logs.length} 筆資料。`;$("exportCsv").disabled=!state.logs.length;renderLogs()}$("loggerToggle").onclick=()=>{if(state.logger){clearInterval(state.logger);state.logger=null;$("loggerToggle").textContent="▶ 開始記錄";$("loggerInfo").textContent=`記錄已停止，共 ${state.logs.length} 筆。`}else{snapshot();state.logger=setInterval(snapshot,Number($("loggerInterval").value));$("loggerToggle").textContent="■ 停止記錄";$("loggerInfo").textContent="記錄中…"}};
function utf16le(text){const bytes=new Uint8Array(2+text.length*2);bytes[0]=255;bytes[1]=254;for(let i=0;i<text.length;i++){const code=text.charCodeAt(i);bytes[2+i*2]=code&255;bytes[3+i*2]=code>>8}return bytes}
$("exportCsv").onclick=()=>{const cols=[...new Set(state.logs.flatMap(x=>Object.keys(x.values)))],rows=[["Time",...cols.flatMap(c=>[`${c} Value`,`${c} Unit`])],...state.logs.map(x=>[x.time,...cols.flatMap(c=>[x.values[c]??"",x.units?.[c]??""])])],tsv=rows.map(r=>r.map(v=>String(v).replaceAll("\t"," ").replaceAll("\r"," ").replaceAll("\n"," ")).join("\t")).join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([utf16le(tsv)],{type:"text/csv;charset=utf-16le"}));a.download=`Lutron-Remote-${Date.now()}.csv`;a.click();URL.revokeObjectURL(a.href)};function resetForNewPair(){if(state.logger){clearInterval(state.logger);state.logger=null;$("loggerToggle").textContent="▶ 開始記錄"}state.readings.clear();state.sourceOrder.clear();state.stats.clear();state.logs=[];$("exportCsv").disabled=true;$("loggerInfo").textContent="尚未開始記錄。";render()}
let resizeStartY=0,resizeStartHeight=0,resizingLog=false;logResizeHandle.addEventListener("pointerdown",event=>{if(logResizeHandle.hidden)return;event.preventDefault();resizingLog=true;resizeStartY=event.clientY;resizeStartHeight=logTableWrap.getBoundingClientRect().height;document.body.classList.add("resizing-log")});window.addEventListener("pointermove",event=>{if(!resizingLog)return;event.preventDefault();const next=Math.max(180,Math.min(760,resizeStartHeight+event.clientY-resizeStartY));logTableWrap.style.height=`${next}px`});window.addEventListener("pointerup",()=>{if(!resizingLog)return;resizingLog=false;document.body.classList.remove("resizing-log")});window.addEventListener("pointercancel",()=>{resizingLog=false;document.body.classList.remove("resizing-log")});input.oninput=()=>input.value=input.value.replace(/\D/g,"").slice(0,6);form.onsubmit=e=>{e.preventDefault();if(input.value.length!==6){setStatus("請輸入正確的 6 位配對碼","failed");return}stop();resetForNewPair();state.code=input.value;state.session++;setStatus("正在加入遠端監看…");connect(state.session)};$("stopButton").onclick=()=>{stop("遠端連線已停止");state.code=""};
})();




